original_image_folder: "./data/binary_codes/original/*.bmp"
modified_image_folder: "./data/binary_codes/modified/*.bmp"
save_model_path: "./model/autoencoder.h5"
model_log_path: "./model/training_log.csv"
binary_code_size: 6
tile_side: 48
step_size: 12
latent_dimension: 32
n_filters: [16, 32]
kernel_size: [[3, 3], [3, 3]]
strides: [[2, 2], [2, 2]]
loss: "mean_squared_error"
initial_learning_rate: .001
early_stopping_patience: 5
max_epochs: 100
batch_size: 32
binary_level_threshold: 0.5
